use script;

insert into roles values (1, 'admin');
insert into roles values (2, 'user');

insert into users values (1, 'admin1@gmail.com', 'admin1', '0123456789', 1, 1);
insert into users values (2, 'admin2@gmail.com', 'admin2', '0123456788', 1, 1);
insert into users values (3, 'user1@gmail.com', 'user1', '0123456787', 1, 2);
insert into users values (4, 'user2@gmail.com', 'user2', '0123456786', 1, 2);

insert into categories values (1, 'Men');
insert into categories values (2, 'Women');
insert into categories values (3, 'Kids');

insert into products values (1, 'Nike Dunk Low Retro', 10, 120, 'Created for the hardwood but taken to the streets, the basketball icon returns with classic details and throwback hoops flair. Channelling 80s vibes, its padded, low-cut collar lets you take your game anywhere—in comfort.', 'static/images/men/dunk-low-retro.jpg', 1, 1);
insert into products values (2, 'Nike Air Force 1 07 LV8', 10, 150, 'Comfortable, durable and timeless—it is number 1 for a reason. The AF-1s classic 80s construction pairs with neutral colours and layered textures for a utilitarian look.', 'static/images/men/air-force-1-07-lv8.jpg', 1, 1);
insert into products values (3, 'Nike Air Max SYSTM', 10, 110, 'Looks Max, feels Max. The Air Max SYSTM brings back everything you love about your favourite 80s vibes (without the parachute trousers). Tried-and-tested visible Nike Air cushioning pairs with a sleek, sport-inspired upper. It is Air Max delivering again.', 'static/images/men/air-max-systm.jpg', 1, 1);
insert into products values (4, 'Nike Air Max Pulse', 10, 190, 'Mixing one-part urban with one-part tough, the Air Max Pulse brings an energetic look to the iconic Air Max line. It combines a textile-wrapped midsole and vacuum-sealed accents to boost its street cred. Point-loaded Nike Air cushioning—revamped from the incredibly plush Air Max 270—delivers the comfort you ve come to trust. Throw them on with your best outfit and go to the max.', 'static/images/men/air-max-pulse.jpg', 1, 1);
insert into products values (5, 'Nike Air Force 1 07', 10, 120, 'The radiance lives on in the Nike Air Force 1 07, the basketball original that puts a fresh spin on what you know best: durably stitched overlays, clean finishes and the perfect amount of flash to make you shine.', 'static/images/men/air-force-1-07.jpg', 1, 1);
insert into products values (6, 'Nike Air Max Ishod', 10, 130, 'Infused with elements taken from iconic 90s hoops shoes, the Air Max Ishod is built with all the durability you need to skate hard. This creative twist on the original Ishod design features updated mesh, exposed Nike Air (with Max Air technology) and a cupsole that breaks in easily. Now step in and skate like you mean it.', 'static/images/men/air-max-ishod.jpg', 1, 1);
insert into products values (7, 'Air Jordan 1 Low G', 10, 190, 'Feel unbeatable, from the tee box to the final putt. Inspired by one of the most iconic sneakers of all time, the Air Jordan 1 G is an instant classic on the course. With Air cushioning underfoot, a Wings logo on the heel and an integrated traction pattern to help you power through your swing, it delivers all the clubhouse cool of the original AJ1—plus everything you need to play 18 holes in comfort.', 'static/images/men/air-jordan-1-low-g-golf.jpg', 1, 1);
insert into products values (8, 'Nike Killshot 2 Leather', 10, 110, 'Inspired by the original tennis shoe, the Killshot 2 updates the classic design with a variety of textured leathers for a fresh look. From soft suedes to smooth leathers with the perfect sheen, it is court-side attitude with a modern touch. To prove you are on top, the dark gum rubber sole adds the cherry on the bottom.', 'static/images/men/killshot-2-leather.jpg', 1, 1);
insert into products values (9, 'Nike Air More Uptempo 96', 10, 210, 'It is all about the A-I-R. The Air More Uptempo 96 refreshes an original that has reigned supreme for more than 20 years. With a design inspired by high-flying basketball style and 90s graffiti art, these kicks can not help but turn heads off court.', 'static/images/men/air-more-uptempo-96.jpg', 1, 1);
insert into products values (10, 'Nike Air Max 97', 10, 200, 'Featuring the original ripple design inspired by Japanese bullet trains, the Nike Air Max 97 lets you push your style full-speed ahead.Taking the revolutionary full-length Nike Air unit that shook up the running world and adding fresh colours and crisp details, it lets you ride in first-class comfort.', 'static/images/men/air-max-97.jpg', 1, 1);

insert into products values (11, 'Nike Dunk Low', 10, 120, 'Created for the hardwood but taken to the streets, the 80s b-ball icon returns with a crisp upper and refreshing colour combos. Channelling vintage style back onto the streets, its padded, low-cut collar lets you take your game anywhere—in comfort.', 'static/images/women/dunk-low.jpg', 1, 2);
insert into products values (12, 'Nike Tech Hera', 10, 110, 'Inspired by early-2000s running, the Tech Hera is here to fulfil all of your chunky sneaker wishes. The wavy lifted midsole and suede accents level up your look while keeping you comfortable. Its durable design holds up beautifully to everyday wear—which is perfect, because you will definitely want to wear these every day.', 'static/images/women/tech-hera.jpg', 1, 2);
insert into products values (13, 'Nike Air Max Excee', 10, 100, 'Inspired by the Nike Air Max 90, the Nike Air Max Excee celebrates a classic through a new lens. Elongated design lines and distorted proportions on the upper elevate an icon into a modern space.', 'static/images/women/air-max-excee.jpg', 1, 2);
insert into products values (14, 'Nike Dunk Low Twist', 10, 110, 'The 80s b-ball icon returns with classic details and throwback hoops flair. Channelling vintage style back onto the streets, its padded collar and extra-puffy silhouette let you take your game anywhere—in comfort.', 'static/images/women/dunk-low-twist.jpg', 1, 2);
insert into products values (15, 'Nike Air Max INTRLK Lite', 10, 100, 'You have got to feel the sensation to be the sensation. Enter the Air Max INTRLK. Rethought cushioning turns the page in comfort with increased responsiveness and the perfect amount of bounce. Lightweight, easy-to-style materials stand up to wear and tear. Finishing it off, the Waffle-inspired outsole adds true Nike zest.', 'static/images/women/air-max-intrlk-lite.jpg', 1, 2);
insert into products values (16, 'Nike Air Max Plus', 10, 210, 'Let your attitude have the edge with this tuned Nike Air experience that offers premium stability and unbelievable cushioning. Featuring classic 90s style, airy mesh and nature-inspired design lines, it lets you show off your defiant style in comfort.', 'static/images/women/air-max-plus.jpg', 1, 2);
insert into products values (17, 'Nike Air Force 1 Wild', 10, 140, 'The outdoors is for everyone—and this shoe is too. The classic AF-1 gets an adventurous refresh with utility lacing, durable materials and sturdy stitching. The textile-wrapped midsole is light and more flexible, while an added heel pillow creates extra comfort. Embroidered accents contrast with boot-like details for a look that is versatile and functional.', 'static/images/women/air-force-1-wild.jpg', 1, 2);
insert into products values (18, 'Nike Court Vision Alta', 10, 130, 'Raise the bar with the Nike Court Vision Alta. The modern design combines leather on top with the perfect lift underneath. The elevated hoops look then crowns your feet with its ultra-plush tongue.', 'static/images/women/court-vision-alta.jpg', 1, 2);
insert into products values (19, 'Nike Air Max Solo', 10, 120, 'This modern interpretation of classic elements is perfect for the Air Max super-fan. Layer up in breathable mesh and plush synthetic leathers, with a heel cup inspired by the AM90. The AM180 influences the textured Air unit, which delivers just the right amount of cushioning. Go ahead—Max out your look.', 'static/images/women/air-max-solo.jpg', 1, 2);
insert into products values (20, 'Nike Air Max AP', 10, 120, 'With its sleek, sporty design, the Nike Air Max AP lets you bridge past and present in first-class comfort. Flashes of heritage detailing nod to the Air Max 97, while the streamlined upper and softer midsole give it a modern edge. The low-profile design with plush padded collar, airy mesh and comfort insole begs to be worn with any outfit.', 'static/images/women/air-max-ap.jpg', 1, 2);

insert into products values (21, 'Nike Air Max SC', 10, 50, 'Simple, comfortable and cushioned with Air—the Nike Air Max SC is an easy yes. The mixture of textures creates a durable and lightweight design little feet can rock all day. Plus, flexible cushioning and an easy strap are everything needed for playtime.', 'static/images/kids/air-max-sc.jpg', 1, 3);
insert into products values (22, 'Nike Tanjun EasyOn', 10, 50, 'Made for kids (and their squirmy feet), these Air Max Shoes have an easy-on system that makes putting them on a breeze. The laces are just for show—the entire lace area lifts up, making a large slip-in space, so getting their shoes on does not have to be a struggle.', 'static/images/kids/tanjun-easyon.jpg', 1, 3);
insert into products values (23, 'Nike Force 1 Low LV8 EasyOn', 10, 70, 'Let your little one style bloom in sneakers that bring serious flower power. Designed to be easy to get on, these shoes are about more than just looking good. The laces are just for show. In fact, the lace area lifts up to give squirmy feet plenty of space to slip in easily. The quick-to-secure strap helps you lock in and adjust the fit. No tying needed!', 'static/images/kids/force-1-low-lv8-easyon.jpg', 1, 3);
insert into products values (24, 'Stay Loyal 3', 10, 60, 'Get your lil one a modern shoe built on the Air Jordan legacy. The design takes nods from the AJ4, so your kid got built-in style with proven lasting power. On top of the minimalist looks, these kicks were made for versatility and ease: on and off is easy with elastic laces and the hook-and-loop strap.', 'static/images/kids/stay-loyal-3.jpg', 1, 3);
insert into products values (25, 'Nike Air Max Excee', 10, 80, 'The Air Max Excee offers a classic Nike look with a fit and feel made for kids. Delivering the support and grip that they need to take those (first!) steps towards independence and play, they are as easy to put on as they are comfortable to wear. No tying needed—elastic laces help to get them on and off quickly.', 'static/images/kids/air-max-excee.jpg', 1, 3);
insert into products values (26, 'Nike Force 1 LV8', 10, 80, 'Little ones can explore the day away in these re-imagined classics. Designed to be durable and easy to style (just like the original AF-1), this Nike Force 1 LV8 features crisp leather and fun colours to help kids enjoy every step. Plus, plush ankle padding helps keep little feet comfy.', 'static/images/kids/force-1-lv8.jpg', 1, 3);
insert into products values (27, 'Nike Court Borough Low Recraft', 10, 40, 'Start your little ones off on the right foot with the Nike Court Borough. Made for the long haul, this recrafted legend uses a combination of durable materials on the upper and outsole to achieve a classic look with an easy-on-and-off strap for entry. Plus, the redesigned toe box and midfoot give their feet a little extra room so they can charge through the day in comfort.', 'static/images/kids/court-borough-low-recraft.jpg', 1, 3);
insert into products values (28, 'Jordan 1 Low Alt', 10, 60, 'Have you got five seconds? Then you have got time to get your kid into these Jordans. The hook-and-loop system makes it easy to open up the shoe and secure it onto little feet. And the look is 100% classic Jordan. They will stay stylish (as if there was any doubt!) and you will stay cool. Win win.', 'static/images/kids/jordan-1-low-alt.jpg', 1, 3);
insert into products values (29, 'Nike Air Max SYSTM', 10, 70, 'Cassette mixtapes. Music videos on TV. Shopping centre arcades. The 80s were fun and wild! We are celebrating that wicked cool era with the Nike Air Max SYSTM. From the big and bold Air unit to design lines (inspired by our favourite throwback Air Max shoes), it is all about bringing back what is cool to a new generation.', 'static/images/kids/air-max-systm.jpg', 1, 3);
insert into products values (30, 'Nike Dynamo 2 EasyOn', 10, 5, 'Awaken your little one inner dragon in the Nike Dynamo 2 EasyOn. Built for any-time play, this soft and plush shoe is all about helping kids get going fast. They can stomp down on the collapsible heel and slip their feet in fast. Or, if they are not quite ready to do it themselves, you can show them how it works by pushing down on the heel.', 'static/images/kids/dynamo-2-easyon.jpg', 1, 3);
